### ISSUE TITLE
Initial setup of woff2-tests repo (eg from woff1 tests)

### ISSUE THREAD

**Issue by rsheeter** [w3c/woff2-tests#1]
Populate woff2-tests, presumably largely from the original woff tests, reorganized as you see fit.

**Comment by khaledhosny** [comment]
What kind of tests we are interested in here? The WOFF spec mentions three test suites:

> The Working Group has developed public test suites as follows:
> - [User Agent tests](http://dev.w3.org/webfonts/WOFF/tests/UserAgent/Tests/xhtml1/testcaseindex.xht)
> - [Authoring Tool tests](http://dev.w3.org/webfonts/WOFF/tests/AuthoringTool/Tests/xhtml1/testcaseindex.xht)
> - Test data for [the file format itself](http://dev.w3.org/webfonts/WOFF/tests/Format/Tests/xhtml1/testcaseindex.xht)

Do we want only the file format test suite, or all of the three.

**Comment by rsheeter** [comment]
I believe we want all three, but my feeling is the priority would be UA tests (eg the render pass/fail in a browser style tests).

**Comment by khaledhosny** [comment]
This should be now more or less done, as we have the scripts in place and they are starting to generate WOFF2 files (sort of, the files are likely to be invalid right now). Next I’ll be working on fixing individual tests.
