### ISSUE TITLE
spec links are not absolute urls

### ISSUE THREAD

**Issue by svgeesus** [w3c/woff2-tests#9]
Looking at the html source of the user agent tests, I see relative rather than absolute urls, for example:

&lt;link rel="help" href="#conform-metadata-noeffect" />

However, it looks as if the code is already in place to generate the correct absolute urls (pointing to the woff1 or woff2 spec as appropriate), but is not being used for some reason:

https://github.com/w3c/woff2-tests/blob/master/generators/testCaseGeneratorLib/html.py
def expandSpecLinks(links):
    """
    This function expands anchor-only references to fully qualified spec links.
    #name expands to <woff2specurl>#name. woff1:#name expands to
    <woff1specurl>#name

This has the unfortunate side effect of foiling my cunning plan to re-use the CSS Working Group test harness to run the user agent tests and gather implementation reports automatically. (Otherwise, all the metadata is correct for that application).

**Comment by svgeesus** [comment]
In other words I need
&lt;link rel="help" href="https://www.w3.org/TR/WOFF2/#conform-metadata-noeffect" />

**Comment by svgeesus** [comment]
Oh, also, the tests show up as "submitted for review" so we also need to add something like
&lt;link rel="reviewer" title="Chris Lilley" href="mailto:chris@w3.org" />

**Comment by svgeesus** [comment]
![woff-not-linked](https://cloud.githubusercontent.com/assets/2506926/17542006/9ad2948a-5ecd-11e6-958a-f6fa0fceef40.png)

**Comment by khaledhosny** [comment]
The links are absolute here, how are you generating/accessing the HTML files?

**Comment by svgeesus** [comment]
I checked the pre-built tests out of https://github.com/w3c/woff2-compiled-tests

**Comment by khaledhosny** [comment]
Ah, I was looking in the test index but you seem to be referring to the individual html files. The code is intentionally making the links relative:
https://github.com/w3c/woff2-tests/blob/master/generators/testCaseGeneratorLib/html.py#L107

I don’t know why it is doing that, but it should be easy to fix if this is what we really want.

**Comment by svgeesus** [comment]
Yes, without absolute links the test harness flags up each test as not testing anything. The links are also used to group together tests for the same feature in the test report.

**Comment by khaledhosny** [comment]
For the reviewer we need to added this exactly `<link rel="reviewer" title="Chris Lilley" href="mailto:chris@w3.org" />` to all test files?

**Comment by svgeesus** [comment]
Yes (well, the email and title could be other people, but can't be an organization or group, so we can't put the fonts wg for example). Only reviewed tests show up in the test harness.

**Comment by khaledhosny** [comment]
OK.

**Comment by khaledhosny** [comment]
Both issues should be fixed now (I hope, I don’t know how to test it).

**Comment by svgeesus** [comment]
Thanks! If https://github.com/w3c/woff2-compiled-tests could be updated with the corrected tests, I can test the CSS test manager integration.

**Comment by rsheeter** [comment]
Just ran the update script, try now?

Is the CSS test manager something we can/should use to validate the test
suite?

**Comment by svgeesus** [comment]
Cheers!
What it provides is 
- a test harness, with pass/fail buttons and moving to the next test
- result collection
- reports

**Comment by svgeesus** [comment]
Looking better now. However I notice that we have several tests (valid-005 is an example) whose specification link is invalid:

https://dev.w3.org/webfonts/WOFF2/spec/#conform-metadata-noeffect

that is because this should link to the WOFF1 spec instead

https://dev.w3.org/webfonts/WOFF/spec/#conform-metadata-noeffect

I recall seeing some code which looked at a prefix to see whether to link to WOFF1 or WOFF2, but maybe that code is not being used?

**Comment by khaledhosny** [comment]
The code is used, but the link was not consistently prefixed. I fixed this one, but I think @rsheeter has some code to check the validity of the links which might help us finding other similar cases.

**Comment by rsheeter** [comment]
From a quick inspection of how the links appear to match up perhaps these need the woff1 prefix?

```
FF 
    conform-metaOrigLength [woff1]
    conform-metadata-alwayscompress [woff1]        
    conform-metadata-vendor-required [woff1]

UA 
    conform-metadata-authoritative [woff1]
    conform-metadata-maydisplay [woff1]
    conform-metaOrigLength [woff1]
    conform-metadata-alwayscompress [woff1]    
    conform-metadata-vendor-required [woff1]
```

**Comment by khaledhosny** [comment]
Thanks @rsheeter, all should be fixed now.

**Comment by rsheeter** [comment]
FYI Khaled finished implementations of all tests and woff2-compiled-tests is updated. @svgeesus, is the validation tool you showed something we can/should use to verify the tests? If so, how do we get/use it?

**Comment by svgeesus** [comment]
I imported the tests into the W3C CSS test suite framework. It did require a change, it turns out the fonts and other resources need to be in a 'support' directory which is special. With that small change the tests worked.

Implementation report:
http://test.csswg.org/harness/results/woff2_dev/grouped/

Test harness
http://test.csswg.org/harness/suite/woff2_dev/

I'm seeing some failures due to OTS (in Firefox and Chrome, not in Edge which does not use OTS) and some failures from the Google WOFF2 decode implementation. A couple of tests I am not seeing either pass or fail, I marked those as 'cannot tell' and will check if I broke the test somehow with my search and replace.

**Comment by svgeesus** [comment]
I'm seeing a valid-009 in compiled tests, Khaled tells me that test should not be there as it is a decoder test not a ua test

**Comment by khaledhosny** [comment]
The resources files are now in “support” directory, I updated also the compiled tests. Please let me know if this is working.

**Comment by fred-wang** [comment]
@khaledhosny I guess this can be closed?

**Comment by khaledhosny** [comment]
I guess so.
